sananth12/ImageScraper

image_scraper/__init__.py
Changed the help message for the --max-images argument. 
Uses os.path.join method to concatenate paths.
=> Added option to save in custom directory

image_scraper/__init__.py, image_scraper/utils.py
Moved the major functionality into utils.py. Importing that in __init__.py and using the functions. Code becomes much more readable.
=> Refactored code

image_scraper/__init__.py, image_scraper/utils.py
You can now specify the image format as shown.
`$ image-scraper -f png jpg`
=> Added option to sepcify formats

image_scraper/__init__.py, image_scraper/utils.py
Use `--max-filesize` to specify file size in bytes
=> Added max filesize option

image_scraper/__init__.py, image_scraper/utils.py
`--dump-urls` to print all the URLs
=> Added option to dump URLs

README.md, README.rst, image_scraper/utils.py
By default, images are saved in images_<domain>
=> Changed default savedir

image_scraper/utils.py, tests/test.py
=> :bug: :green_heart: fixed svg header content-lenth error

tests/test.py
We must check the arguments of Exception
Fixes #49
=> fix python 3 tests

image_scraper/utils.py
=> import exceptions

image_scraper/utils.py, tests/test.py
Using the Exceptions defined instead of using integers
=> :white_check_mark: included exceptions in tests

.travis.yml, image_scraper/utils.py, tests/test.py
Completely works in Python 3 now.
Using latest build in Travis CI.
Imported Exceptions properly.
=> :white_check_mark::art: python3 fix and improved test

image_scraper/mains.py, image_scraper/utils.py, tests/test.py
Previously, there was a lot of exchange of data between functions. Now, all the data is stored in a class and functions operate on data inside that class.
=> Moved all functions into a class.

README.md, README.rst, image_scraper/mains.py, requirements.txt, setup.py
Currently process is listed as
```sh
4763 pts/0    S+     0:00 /bin/python /bin/image-scraper ananth.co.in/test.html
```
On setting process title, it will be listed as
```sh
5480 pts/0    S+     0:00 image-scraper
```
Updated dependencies and README
=> :arrow_up:added proccess title

image_scraper/utils.py
=> Moved to new style python classes.

README.md, image_scraper/mains.py, image_scraper/utils.py, requirements.txt
Creating a threadpool of objects and scraping.
=> scraping using pyThreadpool

image_scraper/utils.py
Proxy URL's can now be used to download images by adding the argument
--proxy-server proxyurl
Note: Support for proxies simultaneously with PhantomJS not yet added
=> Added basic proxy support

image_scraper/utils.py
Fixed PEP8 violations in utils.py.
Renamed proxyURL to proxy_url to comform to the existing formatting.
=> :art: PEP8 and renamed variables.

image_scraper/utils.py
Proxy url being procesed twice is now moved into the argument parsing.
=> :racehorse: Removed redundant proxy url processing.

image_scraper/mains.py, image_scraper/utils.py, tests/test.py
=> Filename pattern

.travis.yml, image_scraper/mains.py, requirements.txt, tests/test.py
=> Moved from SimplePool to ThreadPoolExecutor.

.gitignore, build_deb/ImageScraper.control, build_deb/ImageScraper.postinst, build_deb/build_deb.sh
`bash ./build_deb/build_deb.sh`
=> Added script to build debian file.

build_deb/build_deb.sh
=> Small fix.

README.md, README.rst, image_scraper/mains.py, image_scraper/utils.py
I implemented this functionality because I needed it.
I just want to share it back.
Thanks!
=> Add min filesize
